
name: Android Auto-Sign Release APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate keystore and passwords
        shell: bash
        run: |
          mkdir -p app/keystore
          STORE_PASS=$(openssl rand -hex 16)
          KEY_PASS=$(openssl rand -hex 16)
          echo "STORE_PASS=$STORE_PASS" >> $GITHUB_ENV
          echo "KEY_PASS=$KEY_PASS" >> $GITHUB_ENV
          keytool -genkeypair -v             -keystore app/keystore/itinerary-release.jks             -storetype JKS -keyalg RSA -keysize 2048 -validity 10000             -alias itinerary             -storepass "$STORE_PASS" -keypass "$KEY_PASS"             -dname "CN=Prateek, OU=IT, O=Itinerary, L=Kolkata, S=WB, C=IN"

          cat > keystore.properties <<EOF
          RELEASE_STORE_FILE=app/keystore/itinerary-release.jks
          RELEASE_STORE_PASSWORD=$STORE_PASS
          RELEASE_KEY_ALIAS=itinerary
          RELEASE_KEY_PASSWORD=$KEY_PASS
          EOF

      - name: Gradle build (release)
        run: |
          ./gradlew --no-daemon clean :app:assembleRelease

      - name: Save outputs (APK + keystore + credentials)
        run: |
          echo "Store Password: $STORE_PASS" > signing-credentials.txt
          echo "Key Alias: itinerary" >> signing-credentials.txt
          echo "Key Password: $KEY_PASS" >> signing-credentials.txt

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: itinerary-release.jks
          path: app/keystore/itinerary-release.jks

      - name: Upload Signing Credentials
        uses: actions/upload-artifact@v4
        with:
          name: signing-credentials
          path: signing-credentials.txt
